---
channel: stable
addons:
  roomskills_local_connect:
    repository: ha-addons/roomskills_local_connect
    target: adguard
    image: ghcr.io/ha-addons/roomskills_local_connect/{arch}
  aircast:
    repository: hassio-addons/addon-aircast
    target: aircast
    image: ghcr.io/hassio-addons/aircast/{arch}
