name: "MyStrom2HA"
description: "Server zum Anbinden von MySteom Buttons an HA via MQTT"
url: "https://hub.docker.com/r/computequg/mystrom2ha"
version: "1.0.1"
slug: "mystrom2ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  Webservice_Password: "mystrom2ha"
schema:
  Webservice_Password: "str"
ports:
  32570/tcp: 32570
ports_description:
  7277/tcp: MyStrom2HA Web interface
ingress: true
ingress_port: 32570
