name: "Mystrom2ha"
description: "Server zum Anbinden von MySteom Buttons an HA via MQTT"
url: "https://hub.docker.com/r/computequg/mystrom2ha"
version: "1.0.0"
slug: "mystrom2ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  32570/tcp: 32570
options:
  Webservice_Password: "mystrom2ha"
schema:
  Webservice_Password: "str"
ingress: true
ingress_port: 32570
